version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "06:30"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  reviewers:
  - stefanahman
  ignore:
  - dependency-name: simplecov
    versions:
    - ">= 0.18.a, < 0.19"
  - dependency-name: simplecov
    versions:
    - ">= 0.19.a, < 0.20"
